server:
  port: 1417
# 配置数据源
spring:
  datasource:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hqd
    password: 1415
  data:
    redis:
      host: localhost
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: service-oss
mybatis-plus:
  #打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
aliyun:
  oss:
    file:
      keyid:
      keysecret:
      bucketname:
      endpoint: